---
upstream_project_url: https://github.com/eclipse-bluechi/bluechi
issue_repository: https://github.com/eclipse-bluechi/bluechi
specfile_path: bluechi.spec
upstream_package_name: bluechi
downstream_package_name: bluechi
upstream_tag_template: v{version}

update_release: false

srpm_build_deps:
  - gcc
  - gcc-c++
  - git
  - jq
  - libselinux-devel
  - meson
  - systemd-devel
  - rpm-build

actions:
  post-upstream-clone:
    - bash -c 'git config --global --add safe.directory $(pwd)'
    - bash -c './build-scripts/create-spec.sh'

  get-current-version:
    - bash -c './build-scripts/version.sh'

  create-archive:
    - bash -c 'meson setup builddir 1>&2'
    - bash -c './build-scripts/create-archive.sh'
    - bash -c 'echo bluechi-$PACKIT_PROJECT_VERSION.tar.gz'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - epel-9-x86_64
      - epel-10-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-i386
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
      - fedora-rawhide-x86_64

  - &tests
    job: tests
    trigger: pull_request
    identifier: integration-tests
    fmf_path: tests
    tmt_plan: container
    tf_extra_params:
      test:
        tmt:
          test_filter: tag:testing-farm-container & tier:0
    labels:
      - standard
    env:
      # Enable local provisioning as this is considered dangerous since tmt v1.38.0
      # see https://github.com/teemtee/tmt/pull/3282
      TMT_FEELING_SAFE: 1
      INSTALL_DEPS: "yes"
    targets:
      # Run integration tests on Fedora using CS9 containers, because running integrations tests on CS9 using CS9
      # containers is very flaky
      #
      # This can be set to fedora-rawhide as soon as the following issue gets resolved:
      # https://github.com/containers/podman/issues/22422
      - fedora-latest-stable-x86_64

  - <<: *tests
    identifier: integration-tests-valgrind
    labels:
      - valgrind
    env:
      # Enable local provisioning as this is considered dangerous since tmt v1.38.0
      # see https://github.com/teemtee/tmt/pull/3282
      TMT_FEELING_SAFE: 1
      INSTALL_DEPS: "yes"
      WITH_VALGRIND: "1"

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@centos-automotive-sig"
    project: bluechi-snapshot
    notifications:
      failure_comment:
        message: "BlueChi build failed for merged commit {commit_sha}. Please check logs {logs_url}, packit dashboard {packit_dashboard_url} and external service dashboard {external_dashboard_url}"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-ppc64le
      - centos-stream-9-s390x
      - centos-stream-9-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-ppc64le
      - centos-stream-10-s390x
      - centos-stream-10-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-s390x
      - epel-9-x86_64
      - epel-10-aarch64
      - epel-10-ppc64le
      - epel-10-s390x
      - epel-10-x86_64
      - fedora-all-aarch64
      - fedora-all-i386
      - fedora-all-ppc64le
      - fedora-all-s390x
      - fedora-all-x86_64

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
      - epel-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-branched
      - epel-all
