#!/usr/bin/env python
# SPDX-License-Identifier: GPL-2.0-or-later
#
# vim:sw=4:ts=4:et
import dasbus

from hirte import Hirte

hirte = Hirte()

try:
    hirte.ListNodeUnits("my-node-name")
except dasbus.error.DBusError:
    print("Node not found")
