FROM quay.io/centos/centos:stream9

ARG USERNAME=test-user

RUN dnf install -y dnf-plugin-config-manager
RUN dnf config-manager -y --set-enabled crb && \
    dnf install -y clang-tools-extra gcc make gtk3 \
    meson systemd-devel systemd; dnf -y clean all

RUN useradd -m $USERNAME

WORKDIR /hirte
