#!/usr/bin/env python
# SPDX-License-Identifier: GPL-2.0-or-later
#
# vim:sw=4:ts=4:et
from hirte import Hirte

hirte = Hirte()

hirte.Disable(
    "my-node-name",
    ["chronyd.service", "hirte-agent.service"]
)
