#!/bin/bash -xe
#
# Copyright Contributors to the Eclipse BlueChi project
#
# SPDX-License-Identifier: LGPL-2.1-or-later

additional_opts=$1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SRC_DIR=$SCRIPT_DIR/../src
BUILD_DIR=$SCRIPT_DIR/../builddir
SUBPROJECTS_DIR=$SCRIPT_DIR/../subprojects

ALL_SRC_FILES=$(find $SRC_DIR -name "*.[ch]" \
        ! -path "$SRC_DIR/libbluechi/ini/ini.[ch]" \
        ! -path "$SRC_DIR/libbluechi/hashmap/hashmap.[ch]" \
        ! -path "$SRC_DIR/*/test/**" \
        ! -path "$BUILD_DIR/**")

for src_file in $ALL_SRC_FILES
do
    echo "Linting $src_file..."

    # Header config.h is autogenerated during the build, so it needs to be added manually here as a parameter
    clang-tidy $additional_opts --quiet $src_file -- \
        -I $SRC_DIR \
        -I $BUILD_DIR \
        -I $SUBPROJECTS_DIR/hashmap.c \
        -I $SUBPROJECTS_DIR/inih \
        -Wno-unknown-warning-option \
        -include config.h
done
